booklist/urls.py
from django.urls import path
from booklist.views import list_book,create_book,update_book,delete_book,book_details
urlpatterns = [
    path('',list_book,name='listings'),
    path('addbook/',create_book,name='addbook'),
    path('detailbook/<pk>',book_details,name='detailbook'),
    path('updatebook/<pk>',update_book,name='up_book'),
    path('deletebook/<pk>',delete_book,name='del_book'),
]

app_name='booklist'

crud_operations/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static
from booklist.views import home_page
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page,name='home'),
    path('crud1/', include('booklist.urls',namespace='booklist')),
    path('crud2/', include('post.urls',namespace='post')),
    path('crud3/', include('product.urls',namespace='product')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post.views import all_posts,create_post,detail_post,update_post,delt_post
urlpatterns = [
    path('',all_posts,name='post_list'),
    path('addpost',create_post,name='post_form'),
    path('dpost/<pk>',detail_post,name='det_post'),
    path('updpost/<pk>',update_post,name='upd_post'),
    path('deltpost/<pk>',delt_post,name='del_post'),
]

app_name='post'

product/urls.py
from django.urls import path
from product.views import product_list,add_product,details_product,update_product,delt_product
urlpatterns = [
    path('',product_list,name="product_list"),
    path('addprod/',add_product,name="product_add"),
    path('detailprod/<pk>',details_product,name="product_det"),
    path('updateprod/<pk>',update_product,name="product_upd"),
    path('deleteprod/<pk>',delt_product,name="product_dlt"),
]

app_name='product'

booklist/models.py
from django.db import models

# Create your models here.


class ListingsOfBook(models.Model):
  name=models.CharField(max_length=120)
  price=models.FloatField(null=True,blank=True)
  description=models.TextField()
  image=models.ImageField( upload_to='booklist/images',null=True,blank=True)

  def __str__(self):
    return self.name

post/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.
User=get_user_model()
class Post(models.Model):
  author=models.ForeignKey(User, on_delete=models.CASCADE)
  title=models.CharField(max_length=120)
  description=models.TextField()
  image=models.ImageField(upload_to='post/images',null=True)
  date_posted=models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.title

product/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
  name=models.CharField( max_length=50)
  description=models.TextField()
  price=models.FloatField()
  in_stock=models.BooleanField()
  number=models.IntegerField()
  image=models.ImageField(upload_to='products/images',null=True,blank=True)


  def __str__(self):
    return self.name

booklist/forms.py
from django.forms import ModelForm
from booklist.models import ListingsOfBook


class AddBookForm(ModelForm):
  class Meta:
    model=ListingsOfBook
    fields="__all__"

post/forms.py
from django.forms import ModelForm
from post.models import Post

class PostCreateForm(ModelForm):
  class Meta:
    model=Post
    fields="__all__"

product/forms.py
from django.forms import ModelForm
from product.models import Product

class ProductAddForm(ModelForm):
  class Meta:
    model=Product
    fields='__all__'

booklist/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.urls import reverse,reverse_lazy
from booklist.models import ListingsOfBook
from booklist.forms import AddBookForm
# Create your views here.
# Home page
def home_page(request):
  return render(request, 'index.html')
# CRUD-1 Booklist
# Listing Books
def list_book(request):
  booklist=ListingsOfBook.objects.all()
  context={
    "booklist":booklist
  }
  return render(request, 'booklist.html',context)

# Create Books
def create_book(request):
  form=AddBookForm()
  context={
    "form":form
  }
  if request.method =="POST":
    form=AddBookForm(request.POST,request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/crud1")

  return render (request, 'addbook.html',context)



# Update Book Details
def update_book(request,pk):
  book=ListingsOfBook.objects.get(id=pk)
  form=AddBookForm(instance=book)
  context={
    "form":form
  }
  if request.method =="POST":
    form=AddBookForm(request.POST, instance=book, files=request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/crud1")
  return render(request, 'updatebook.html',context)

# Delete Book 
def delete_book(request,pk):
  book=ListingsOfBook.objects.get(id=pk)
  book.delete()
  return render(request, 'deletebook.html')





# Detail of Book 
def book_details(request,pk):
  book=ListingsOfBook.objects.get(id=pk)
  context={
    "book":book
  }

  return render(request, 'bookdetails.html',context)

post/views.py
from django.shortcuts import render,redirect
from post.models import Post
from post.forms import PostCreateForm
# Create your views here.
#listing Post
def all_posts(request):
  post=Post.objects.all()
  context={
    "post":post
  }
  return render(request, 'postlist.html', context)


# Create post 
def create_post(request):
  form=PostCreateForm()
  context={
    "form":form
  }
  if request.method =="POST":
    form=PostCreateForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/crud2")
  return render(request, 'createpost.html',context)


def detail_post(request,pk):
  data=Post.objects.get(id=pk)
  context={
    "data":data
  }
  return render(request, "postdetails.html",context)


def update_post(request,pk):
  post=Post.objects.get(id=pk)
  form=PostCreateForm(instance=post)
  context={
    "form":form
  }
  if request.method == "POST":
    form=PostCreateForm(request.POST, instance=post, files=request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/crud2")

  return render(request, "updatepost.html",context)


def delt_post(request,pk):
  post=Post.objects.get(id=pk)
  post.delete()
  return render(request, 'deltbook.html')

product/views.py
from django.shortcuts import render,redirect
from product.models import Product
from product.forms import ProductAddForm
# Create your views here.
# product listing
def product_list(request):
  product=Product.objects.all()
  context={
    "product":product
  }
  return render(request, 'prodlist.html',context)
# product add
def add_product(request):
  form=ProductAddForm()
  context={
    "form":form
  }
  if request.method == "POST":
    form=ProductAddForm(request.POST,request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/crud3")
  return render(request, 'addproduct.html',context)


# product details
def details_product(request,pk):
  prod=Product.objects.get(id=pk)
  context={
    "product":prod
  }
  return render(request,'proddetails.html',context)


# product update 
def update_product(request,pk):
  product=Product.objects.get(id=pk)
  form=ProductAddForm(instance=product)
  context={
    "form":form
  }
  if request.method == "POST":
    form=ProductAddForm(request.POST, instance=product, files=request.FILES)
    if form.is_valid():
      form.save()
      return redirect("/crud3")

  return render(request, "updateproduct.html",context)




# Delete product 

def delt_product(request,pk):
  product=Product.objects.get(id=pk)
  product.delete()
  return render(request, 'deltproduct.html')

booklist/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  {% comment %} Navbar Start {% endcomment %}
  <header class="text-gray-600 body-font mb-4">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a href="{% url 'home' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Crud Operations</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <a href="{% url 'home' %}" class="mr-5 px-2 py-3 hover:bg-gray-700 rounded-xl hover:text-white hover:shadow-xl">Home</a>
        <a href="{% url 'booklist:listings' %}" class="mr-5 px-2 py-3 hover:bg-gray-700 rounded-xl hover:text-white hover:shadow-xl">Booklist</a>
        <a href="{% url 'post:post_list' %}" class="mr-5 px-2 py-3 hover:bg-gray-700 rounded-xl hover:text-white hover:shadow-xl">BlogPost</a>
        <a href="{% url 'product:product_list' %}" class="mr-5 px-2 py-3 hover:bg-gray-700 rounded-xl hover:text-white hover:shadow-xl">Ecomerce Product</a>
      </nav>
      <a href="https://github.com/talhakhan54" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">About Me
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </div>
  </header>
  {% comment %} Navbar End {% endcomment %}

  {% block body %}{% endblock body %}

  {% comment %} Footer Start {% endcomment %}
  <footer class="mt-4 text-gray-600 body-font position-static">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
      <a href="{% url 'home' %}" class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Crud Operations</span>
      </a>
      <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2020 Tailblocks —
        <a href="https://twitter.com/knyttneve" class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">@knyttneve</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a class="text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
  </footer>
  {% comment %} Footer End {% endcomment %}
</body>

</html>

booklist/templates/bookdetails.html
{% extends 'base.html'%}
{% block title %}Detail of {{book.name}}{% endblock title %}
{% block body %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
      <img class="object-cover object-center rounded" alt="hero" src="{{book.image.url}}">
    </div>
    <div
      class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">{{book.name}}
      </h1>
      <div class="mb-8 leading-relaxed">{{book.description}}</div>
      {% if user.is_authenticated %}
      <div class="">
        <a href="{% url 'booklist:up_book' book.id %}"
          class="bg-blue-500 hover:bg-blue-700 rounded-xl ml-2 px-2 py-3 shadow-xl font-bold text-white mt-2 text-center">Update
          Details</a>
        <a href="{% url 'booklist:del_book' book.id %}"
          class="bg-blue-500 hover:bg-blue-700 rounded-xl ml-2 px-2 py-3 shadow-xl font-bold text-white mt-2 text-center">Delete
          Book</a>
      </div>
      {% endif %}
    </div>
  </div>
</section>

{% endblock body %}

booklist/templates/booklist.html
{% extends 'base.html' %}
{% block title %}List Of Books{% endblock title %}
{% block body %}


<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap w-full mb-20">
      <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Listings of all Books.</h1>
        <div class="h-1 w-20 bg-indigo-500 rounded"></div>
      </div>
      <p class="lg:w-1/2 w-full leading-relaxed text-gray-500">Welcome to our bookshop. We have all the books listed here. Choice one and buy. Thank you.</p>
    </div>
    <div class="flex flex-wrap -m-4">
      {% for list in booklist %}
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          <img class="h-40 rounded w-full object-cover object-center mb-6" src="{{list.image.url}}" alt="content">
          <a href="{% url 'booklist:detailbook' list.id %}" class="text-xl text-gray-900 font-medium title-font mb-4">{{list.name}}</a>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4 mt-2">${{list.price}}</h2>
          
        </div>
      </div>
      {% endfor %}
      <a href="{% url 'booklist:addbook' %}" class="my-auto text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2  dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add a New Book</a>

    </div>
  </div>
</section>



{% endblock body %}

booklist/templates/deletebook.html
{% extends 'base.html' %}
{% block title %}Book Deleted{% endblock title %}
{% block body %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
      <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Your Book is Deleted.</h1>
      <a href="{% url 'booklist:listings' %}" class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Go Back</a>
    </div>
  </div>
</section>
{% endblock body %}

booklist/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block body %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4">
      <div class="p-4 lg:w-1/3">
        <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
          <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">CRUD Operation-1</h2>
          <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">CRUD Operation on Booklist</h1>
          <p class="leading-relaxed mb-3">Here is a crud opeartion on booklist for a bookshop.</p>
          <a href="{% url 'booklist:listings' %}" class="text-indigo-500 inline-flex items-center">Check The CRUD
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          </a>
          
        </div>
      </div>
      <div class="p-4 lg:w-1/3">
        <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
          <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">CRUD Operation-2</h2>
          <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">CRUD Operation on Post</h1>
          <p class="leading-relaxed mb-3">Here is a crud opeartion on posts for a blogpost site.</p>
          <a href="{% url 'post:post_list' %}" class="text-indigo-500 inline-flex items-center">Check the CRUD
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
      <div class="p-4 lg:w-1/3">
        <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
          <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">CRUD Operation-3</h2>
          <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">CRUD operation on Product</h1>
          <p class="leading-relaxed mb-3">Here is a crud operation on products for an ecomerce website.</p>
          <a href="{% url 'product:product_list' %}" class="text-indigo-500 inline-flex items-center">Check the CRUD
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock body %}

post/templates/deltbook.html
{% extends 'base.html' %}
{% block title %}Your Post is deleted{% endblock title %}
{% block body %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
      <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Your Post is Deleted. </h1>
      <a href="{% url 'post:post_list' %}" class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Go Back</a>
    </div>
  </div>
</section>
{% endblock body %}

post/templates/postdetails.html
{% extends 'base.html' %}
{% block title %}{{data.title}}{% endblock title %}
{% block body %}
<div class="container m-auto">
  <div class="flex justify-center">
    <div class="flex flex-col justify-center">
      <div class="flex flex-col md:flex-row max-w-7xl justify-center items-center ">
        <div class="overflow-hidden w-full m-4 shadow-sm flex flex-col md:flex-row justify-center">
          <div class="flex flex-col md:flex-row items-center">
            <div class=" w-full overflow-hidden"> <img src="{{data.image.url}}" alt="" class="" /> </div>
            <div class="md:w-2/3 m-4 ">
              <div class="flex text-gray-500 text-sm m-2">
                <div class="m-1">{{data.date_posted}}</div>
              </div>
              <div class="font-bold text-black text-xl m-2">{{data.title}} </div>
              <div class="text-sm text-gray-500 mt-4 m-2">{{data.description}}</div>
              <div class="flex cursor-pointer mt-5">
                <div class="m-2"> <img src="" alt="" class=" rounded-full" />
                </div>
                <div class="grid m-1">
                  <div class="font-bold text-sm hover:text-gray-600 mt-2">{{data.author}} </div>
                </div>
                {% if user.is_authenticated %}
                <div class="ml-5 ">
                  <a href="{% url 'post:upd_post' data.id %}"
                    class="bg-indigo-600 hover:bg-indigo-700 rounded-xl ml-2 px-2 py-3 shadow-xl font-bold text-white mt-2 text-center">Update
                    Post</a>
                  <a href="{% url 'post:del_post' data.id %}"
                    class="bg-indigo-600 hover:bg-indigo-700 rounded-xl ml-2 px-2 py-3 shadow-xl font-bold text-white mt-2 text-center">Delete
                    Post</a>
                </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://use.fontawesome.com/03f8a0ebd4.js"></script>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</div>


{% endblock body %}

post/templates/postlist.html
{% extends 'base.html' %}
{% block title %}Post from Different Users{% endblock title %}
{% block body %}
<div class="container m-auto">
  <section class="text-gray-600 body-font overflow-none mb-12">
    <div class="container px-5 mx-auto">
      {% for post in post %}
      <div class="-my-8 divide-y-2 divide-gray-100 bg-slate-300 px-3 py-2 rounded-xl shadow-xl mt-20">
        <div class="py-8 flex flex-wrap md:flex-nowrap">
          <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
            <span class="font-semibold title-font text-gray-700">{{post.author}}</span>
            <span class="mt-1 text-gray-500 text-sm">{{post.date_posted}}</span>
          </div>
          <div class="md:flex-grow">
            <h2 class="text-2xl font-medium text-gray-900 title-font mb-2">{{post.title}}</h2>
            <span class="overflow-scroll">
              <p class="leading-relaxed">{{post.description|safe|truncatewords:"50"|linebreaks}}</p>
            </span>
            <a href="{% url 'post:det_post' post.id %}" class="text-indigo-500 inline-flex items-center mt-4">Read More
              <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none"
                stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  <a href="{% url 'post:post_form' %}"
    class="mx-5 shadow-xl flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Add
    a new Post</a>
</div>

{% endblock body %}

product/templates/proddetails.html
{% extends 'base.html' %}
{% block title %}Detail of {{product.name}}{% endblock title %}
{% block body %}
<div class="container m-auto">
  
<div class="container m-auto">
  <div class="flex justify-center">
    <div class="flex flex-col justify-center">
      <div class="flex flex-col md:flex-row max-w-7xl justify-center items-center ">
        <div class="overflow-hidden w-full m-4 shadow-sm flex flex-col md:flex-row justify-center">
          <div class="flex flex-col md:flex-row items-center">
            <div class=" w-full overflow-hidden"> <img src="{{product.image.url}}" alt="" class="" /> </div>
            <div class="md:w-2/3 m-4 ">
              <div class="flex text-gray-500 text-sm m-2">
                <div class="m-1">{{data.date_posted}}</div>
              </div>
              <div class="font-bold text-black text-3xl m-2">{{product.name}} </div>
              <div class="text-sm text-gray-500 mt-4 m-2">{{product.description}}</div>
              <div class="flex items-center justify-evenly mt-5">
                <div class="m-1">
                  <div class="font-bold text-xl hover:text-gray-600 mt-2">${{product.price}} </div>
                </div>
                <div class="">
                  <button class="flex ml-auto text-white bg-indigo-600 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-700 rounded">Buy Now</button>
                </div>
              </div>
              <div class="flex flex-col items-stretch   mt-5">
                {% if user.is_authenticated %}
                <div class="mt-6">
                  <a href="{% url 'product:product_upd' product.id %}"
                    class="bg-indigo-600 hover:bg-indigo-700 rounded-xl ml-2 px-2 py-3 shadow-xl font-bold text-white mt-2 text-center">Update
                    Product</a>
                </div>
                <div class="mt-8">
                  <a href="{% url 'product:product_dlt' product.id %}"
                    class="bg-indigo-600 hover:bg-indigo-700 rounded-xl ml-2 px-2 py-3 shadow-xl font-bold text-white mt-2 text-center">Delete
                    Product</a>
                  </div>
                {% endif %}
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://use.fontawesome.com/03f8a0ebd4.js"></script>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</div>
</div>
{% endblock body %}